### ISSUE TITLE
bug in add owner functionality.

### ISSUE THREAD

**Issue by barPerlman** [RonAsis/Wsep202#223]
2020-06-18 08:51:09 - started session of registration for user: u2
2020-06-18 08:51:10 - The user u2 got encrypted password and salt
2020-06-18 08:51:10 - The user u2 registering
2020-06-18 08:51:10 - started session of registration for user: u3
2020-06-18 08:51:10 - The user u3 got encrypted password and salt
2020-06-18 08:51:10 - The user u3 registering
2020-06-18 08:51:10 - started session of registration for user: u4
2020-06-18 08:51:10 - The user u4 got encrypted password and salt
2020-06-18 08:51:10 - The user u4 registering
2020-06-18 08:51:10 - started session of registration for user: u5
2020-06-18 08:51:10 - The user u5 got encrypted password and salt
2020-06-18 08:51:10 - The user u5 registering
2020-06-18 08:51:10 - started session of registration for user: u6
2020-06-18 08:51:10 - The user u6 got encrypted password and salt
2020-06-18 08:51:10 - The user u6 registering
2020-06-18 08:51:11 - user: u2 logged in successfully, is admin: false
2020-06-18 08:51:11 - added a new owned OR managed store 's1' to the user 'u2'
2020-06-18 08:51:11 - A new store 's1' was opened in the system, u2 is the owner
2020-06-18 08:51:11 - user u3 waiting for be approve in store '1'
2020-06-18 08:51:11 - added a new owned OR managed store 's1' to the user 'u3'
2020-06-18 08:51:11 - SQL Error: 1062, SQLState: 23000
2020-06-18 08:51:11 - (conn:2004) Duplicate entry '1-u3' for key 'PRIMARY'
Query is: insert into owners_appointee_appointed_users (owners_appointee_id, appointed_users_user_name) values (?, ?), parameters [1,'u3']
2020-06-18 08:51:11 - HHH000010: On release of batch it still contained JDBC statements
2020-06-18 08:51:11 - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2020-06-18 08:51:11 - Application run failed
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:778)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:765)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.wsep202.TradingSystem.TradingSystemApplication.main(TradingSystemApplication.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [PRIMARY]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:298)
	at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:255)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:538)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.processCommit(AbstractPlatformTransactionManager.java:743)
	at org.springframework.transaction.support.AbstractPlatformTransactionManager.commit(AbstractPlatformTransactionManager.java:711)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.commitTransactionAfterReturning(TransactionAspectSupport.java:631)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:385)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:118)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:178)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
	at com.sun.proxy.$Proxy172.save(Unknown Source)
	at com.wsep202.TradingSystem.domain.trading_system_management.TradingSystemDataBaseDao.updateStoreAndUserSystem(TradingSystemDataBaseDao.java:188)
	at com.wsep202.TradingSystem.domain.trading_system_management.TradingSystemDataBaseDao$$FastClassBySpringCGLIB$$8b99da5e.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.wsep202.TradingSystem.domain.trading_system_management.TradingSystemDataBaseDao$$EnhancerBySpringCGLIB$$706a056c.updateStoreAndUserSystem(<generated>)
	at com.wsep202.TradingSystem.domain.trading_system_management.TradingSystem.addOwnerToStore(TradingSystem.java:388)
	at com.wsep202.TradingSystem.domain.trading_system_management.TradingSystemFacade.addOwner(TradingSystemFacade.java:318)
	at com.wsep202.TradingSystem.dynamic_start_up.AddOwnerDefinition.apply(AddOwnerDefinition.java:34)
	at com.wsep202.TradingSystem.AppStartupRunner.lambda$null$0(AppStartupRunner.java:79)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at com.wsep202.TradingSystem.AppStartupRunner.lambda$doActions$1(AppStartupRunner.java:79)
	at java.util.Optional.ifPresent(Optional.java:159)
	at com.wsep202.TradingSystem.AppStartupRunner.doActions(AppStartupRunner.java:78)
	at com.wsep202.TradingSystem.AppStartupRunner.initialAccordingByFiles(AppStartupRunner.java:65)
	at com.wsep202.TradingSystem.AppStartupRunner.run(AppStartupRunner.java:47)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:775)
	... 10 common frames omitted
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
	at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59)
	at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
	at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200)
	at org.hibernate.engine.jdbc.batch.internal.NonBatchingBatch.addToBatch(NonBatchingBatch.java:45)
	at org.hibernate.persister.collection.AbstractCollectionPersister.insertRows(AbstractCollectionPersister.java:1593)
	at org.hibernate.action.internal.CollectionUpdateAction.execute(CollectionUpdateAction.java:89)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:604)
	at org.hibernate.engine.spi.ActionQueue.lambda$executeActions$1(ActionQueue.java:478)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.hibernate.engine.spi.ActionQueue.executeActions(ActionQueue.java:475)
	at org.hibernate.event.internal.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:348)
	at org.hibernate.event.internal.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:40)
	at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:102)
	at org.hibernate.internal.SessionImpl.doFlush(SessionImpl.java:1352)
	at org.hibernate.internal.SessionImpl.managedFlush(SessionImpl.java:443)
	at org.hibernate.internal.SessionImpl.flushBeforeTransactionCompletion(SessionImpl.java:3202)
	at org.hibernate.internal.SessionImpl.beforeTransactionCompletion(SessionImpl.java:2370)
	at org.hibernate.engine.jdbc.internal.JdbcCoordinatorImpl.beforeTransactionCompletion(JdbcCoordinatorImpl.java:447)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.beforeCompletionCallback(JdbcResourceLocalTransactionCoordinatorImpl.java:183)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl.access$300(JdbcResourceLocalTransactionCoordinatorImpl.java:40)
	at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.commit(JdbcResourceLocalTransactionCoordinatorImpl.java:281)
	at org.hibernate.engine.transaction.internal.TransactionImpl.commit(TransactionImpl.java:101)
	at org.springframework.orm.jpa.JpaTransactionManager.doCommit(JpaTransactionManager.java:534)
	... 40 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: (conn:2004) Duplicate entry '1-u3' for key 'PRIMARY'
Query is: insert into owners_appointee_appointed_users (owners_appointee_id, appointed_users_user_name) values (?, ?), parameters [1,'u3']
	at org.mariadb.jdbc.internal.util.ExceptionMapper.get(ExceptionMapper.java:133)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.getException(ExceptionMapper.java:101)
	at org.mariadb.jdbc.internal.util.ExceptionMapper.throwAndLogException(ExceptionMapper.java:77)
	at org.mariadb.jdbc.MariaDbStatement.executeQueryEpilog(MariaDbStatement.java:224)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:411)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.execute(MariaDbServerPreparedStatement.java:361)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeUpdate(MariaDbServerPreparedStatement.java:350)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java)
	at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197)
	... 60 common frames omitted
Caused by: org.mariadb.jdbc.internal.util.dao.QueryException: Duplicate entry '1-u3' for key 'PRIMARY'
Query is: insert into owners_appointee_appointed_users (owners_appointee_id, appointed_users_user_name) values (?, ?), parameters [1,'u3']
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readErrorPacket(AbstractQueryProtocol.java:1098)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.readPacket(AbstractQueryProtocol.java:1030)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.getResult(AbstractQueryProtocol.java:985)
	at org.mariadb.jdbc.internal.protocol.AbstractQueryProtocol.executePreparedQuery(AbstractQueryProtocol.java:571)
	at org.mariadb.jdbc.MariaDbServerPreparedStatement.executeInternal(MariaDbServerPreparedStatement.java:399)
	... 65 common frames omitted
2020-06-18 08:51:11 - Stopping...
2020-06-18 08:51:11 - BrokerAvailabilityEvent[available=false, SimpleBrokerMessageHandler [DefaultSubscriptionRegistry[cache[0 destination(s)], registry[0 sessions]]]]
2020-06-18 08:51:11 - Stopped.
2020-06-18 08:51:11 - Shutting down ExecutorService 'brokerChannelExecutor'
2020-06-18 08:51:11 - Shutting down ExecutorService 'messageBrokerTaskScheduler'
2020-06-18 08:51:11 - Shutting down ExecutorService 'clientOutboundChannelExecutor'
2020-06-18 08:51:11 - Shutting down ExecutorService 'clientInboundChannelExecutor'
2020-06-18 08:51:11 - Closing JPA EntityManagerFactory for persistence unit 'default'
2020-06-18 08:51:11 - HikariPool-1 - Shutdown initiated...
2020-06-18 08:51:11 - HikariPool-1 - Shutdown completed.

Process finished with exit code 1

**Comment by RonAsis** [comment]
The bag is fix alone

**Comment by KseniaDr** [comment]
1. one owner in store trys to add second owner, second owner is not in owner list.
2. owner can add himself as manager.
